name: Test support go fmt

on:
  push:
    branches:
      - '*'

jobs:
  test:
    strategy:
      matrix:
        envinfo:
          - { name: 'linux-3.6-x64', os: ubuntu-latest, python-version: 3.6.x, python-arch: x64, TZ: 'Asia/Shanghai' }

    env:
        PYTHONIOENCODING: "utf-8"
        PYTHONHASHSEED: 32
        TZ: ${{ matrix.envinfo.TZ }}
        TESTLOGPATH: "./log_archive/"
        TESTLOGNAME: ${{ matrix.envinfo.name }}

    runs-on: ${{ matrix.envinfo.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: gofmt 0
      uses: shinny-hongyan/gofmt-action@master
      with:
        gofmt-path: '.'

    - name: gofmt
      shell: bash
      id: gofmtchk
      run: |
        REPORT=$(find . -name "*.go" | grep -v vendor | xargs -L1 -P8 go fmt)
        echo "::set-env name=GOFMT_OUTPUT::$REPORT"
        echo "All the following files are not correctly formatted"
        echo $REPORT
        

    - name: gofmt 2
      shell: bash
      run: |
        exit 1
