name: Test support go fmt

on:
  push:
    branches:
      - '*'

jobs:
  test:
    strategy:
      matrix:
        envinfo:
          - { name: 'linux-3.6-x64', os: ubuntu-latest, python-version: 3.6.x, python-arch: x64, TZ: 'Asia/Shanghai' }

    env:
        PYTHONIOENCODING: "utf-8"
        PYTHONHASHSEED: 32
        TZ: ${{ matrix.envinfo.TZ }}
        TESTLOGPATH: "./log_archive/"
        TESTLOGNAME: ${{ matrix.envinfo.name }}

    runs-on: ${{ matrix.envinfo.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: gofmt
      shell: bash
      id: gofmtchk
      run: |
        REPORT=$(find . -name "*.go" | grep -v vendor | xargs -L1 -P8 go fmt)
        echo $REPORT
        REPORT="${REPORT//'%'/'%25'}"
        REPORT="${REPORT//$'\n'/'%0A'}"
        REPORT="${REPORT//$'\r'/'%0D'}"
        echo $REPORT
        echo "::set-output name=GOFMT_OUTPUT::$REPORT"

    - name: gofmt 2
      if: ${{ steps.gofmtchk.outputs.GOFMT_OUTPUT != '' }}
      shell: bash
      run: |
        echo "All the following files are not correctly formatted"
        echo ${{ steps.gofmtchk.outputs.GOFMT_OUTPUT}}
        exit 1
